version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: passwd
      MYSQL_DATABASE: db_aula
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./carga.sql:/docker-entrypoint-initdb.d/carga.sql 

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data:
